#!/bin/bash

# Lanzador de aplicaciones bajo el boton de menu de la polybar

rofi -no-lazy-grab -show drun -terminal ~/.config/bspwm/scripts/terminal \
	-theme-str 'window { location: north west; anchor: north west; x-offset: 10px; y-offset: 32px; width: 22%; }'
