#!/bin/bash

# Lanzador de aplicaciones a pantalla completa

rofi -no-lazy-grab -show drun -terminal ~/.config/bspwm/scripts/terminal -theme-str 'window { fullscreen: true; } mainbox { padding: 12% 25%; }'
