#!/bin/bash

# Menu de apagado bajo el boton de la polybar

MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'Sistema' \
	-theme-str 'window { location: north east; anchor: north east; x-offset: -10px; y-offset: 32px; width: 12%; } listview { lines: 4; }' \
	<<< "  Lock|  Logout|  Reboot|  Shutdown")"
case "$MENU" in
  *Lock) i3lock -c 000000 ;;
  *Logout) bspc quit ;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl -i poweroff
esac
