#!/bin/bash

# Menu de apagado centrado

MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'Sistema' \
	-theme-str 'window { width: 12%; } listview { lines: 4; }' \
	<<< "  Lock|  Logout|  Reboot|  Shutdown")"
case "$MENU" in
  *Lock) i3lock -c 000000 ;;
  *Logout) bspc quit ;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl -i poweroff
esac
